const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const ts=require('typescript');
require.extensions['.ts']=(module,path)=>module._compile(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,path);
const m=require('../lib/finserv-workflow.ts');
function staged(){let w=m.createWorkflow();w.briefConfirmed=true;w.contacts=w.contacts.map(c=>({...c,matched:true,excluded:!c.eligible}));w.audienceConfirmed=true;w.assets=m.generateAssets(w);w.reviews=Object.fromEntries(m.reviewers.map(r=>[r,'Approved']));for(const c of m.channels)w.handoffs[c].staged=true;return w;}
test('incomplete direction, audience, content, reviews and handoffs gate progression',()=>{const w=m.createWorkflow();for(let i=0;i<6;i++)assert.ok(m.blockers(w,i).length);assert.equal(m.audienceReady(w),false);});
test('eligible subset can continue while unresolved contact permission remains excluded',()=>{const w=staged();assert.equal(m.audienceReady(w),true);for(let i=0;i<5;i++)assert.deepEqual(m.blockers(w,i),[]);assert.ok(m.blockers(w,5).length);w.launched=true;assert.deepEqual(m.blockers(w,5),[]);});
test('both tracks have all channel drafts and edits to source direction propagate',()=>{let w=staged();assert.equal(w.assets.length,28);for(const track of ['Top 20','Broader market'])for(const channel of m.channels)assert.ok(w.assets.some(a=>a.track===track&&a.channel===channel));w.instruction='Focus on procurement';w.source='governance';const a=m.generateAssets(w);assert.match(a.find(a=>a.id==='top-sponsor-guide').body,/Focus on procurement/);assert.match(a.find(a=>a.id==='broad-web').body,/Responsible Evaluation/);w.source='missing';assert.deepEqual(m.generateAssets(w),[]);});
test('approval requires each reviewer and every channel requires owner and staging',()=>{let w=staged();w.reviews.Morgan='Changes requested';assert.equal(m.approved(w),false);assert.ok(m.blockers(w,4).length);w.reviews.Morgan='Approved';w.handoffs.Email.owner='';assert.ok(m.blockers(w,4).length);});
test('events cannot run before activation or against excluded records',()=>{let w=staged();assert.equal(m.advanceContact(w,'contact-0','capture'),w);w.launched=true;assert.equal(m.advanceContact(w,'contact-5','capture'),w);assert.equal(m.advanceContact(w,'contact-0','attend'),w);});
test('Top 20 broad entry routes once, sales follows event engagement, counts deduplicate',()=>{let w=staged();w.launched=true;for(const event of ['capture','download','register','attend','accept','follow','meeting','held'])w=m.advanceContact(w,'contact-0',event);const c=w.contacts[0];assert.match(c.log.join(' '),/duplicate guide and webinar invitation suppressed/);assert.equal(m.salesReady(c),true);assert.equal(c.meetingHeld,true);assert.equal(m.measures(w).captured,1);assert.equal(m.measures(w,true).captured,1);assert.equal(m.measures(w).held,1);assert.equal(m.advanceContact(w,'contact-0','capture'),w);});
test('broader finance registrants stay nurtured until direct meeting request',()=>{let w=staged();w.launched=true;for(const e of ['capture','download','register','attend'])w=m.advanceContact(w,'contact-3',e);assert.equal(m.salesReady(w.contacts[3]),false);assert.equal(m.advanceContact(w,'contact-3','accept'),w);w=m.advanceContact(w,'contact-3','meeting');assert.equal(m.salesReady(w.contacts[3]),true);});
test('non-downloaders get proof without unlocking event invitations',()=>{let w=staged();w.launched=true;w=m.advanceContact(w,'contact-1','capture');w=m.advanceContact(w,'contact-1','proof');assert.equal(w.contacts[1].proof,true);assert.equal(m.advanceContact(w,'contact-1','register'),w);});
test('editing resets reviews, staging and old simulation results',()=>{let w=staged();w.launched=true;w=m.advanceContact(w,'contact-0','capture');const n=m.invalidate(w);assert.equal(n.revision,w.revision+1);assert.equal(n.launched,false);assert.equal(m.approved(n),false);assert.equal(m.measures(n).captured,0);assert.ok(m.channels.every(c=>!n.handoffs[c].staged));assert.equal(n.contacts[5].excluded,true);});
test('saved state round trips and rejects malformed contacts and artifacts',()=>{let w=staged();w.launched=true;w=m.advanceContact(w,'contact-0','capture');assert.deepEqual(m.restoreWorkflow(JSON.parse(JSON.stringify(w))),w);assert.throws(()=>m.restoreWorkflow({...w,contacts:[null]}));assert.throws(()=>m.restoreWorkflow({...w,assets:[{id:'bad'}]}));assert.deepEqual(m.restoreWorkflow({version:1}),m.createWorkflow());});
test('export includes reviewed copy, owners, evidence, actions and learning',()=>{const w=staged();w.assets[0].title='Edited ad';w.learning='Close handoffs faster';w.appliedLearning=w.learning;const text=m.workflowReadout(w);for(const expected of ['Edited ad','Morgan: Approved','Marketing operations','Close handoffs faster','No actual campaign results'])assert.ok(text.includes(expected),expected);});
