import type { Asset } from "../lib/finserv-workflow";
import { assetCopy, eventTiming, guideTitle } from "../lib/finserv-asset-design";
const Mark=()=> <span className="oa-wordmark">OpenAI</span>;
const Cta=({children}:{children:React.ReactNode})=><span className="oa-cta">{children}<span aria-hidden="true">↗</span></span>;
function Guide({asset,small=false}:{asset:Asset;small?:boolean}){return <div className={`oa-guide${small?" oa-guide-small":""}`}><Mark/><div><span className="oa-eyebrow">A guide for financial services</span><h3>{guideTitle(asset)}</h3></div><div className="oa-guide-lines" aria-hidden="true">{Array.from({length:11},(_,i)=><i key={i} style={{width:`${100-i*6}%`}}/>)}</div><span className="oa-guide-bottom">A practical starting point<br/>for your next evaluation.</span></div>;}
function Footer(){return <footer className="oa-footer"><Mark/><span>Financial services</span><span>Privacy · Email preferences</span></footer>;}
function Copy({asset}:{asset:Asset}){return <>{assetCopy(asset).map((p,i)=><p key={i}>{p}</p>)}</>;}
function Website({asset}:{asset:Asset}){return <div className="oa-web"><nav className="oa-site-nav"><Mark/><span>For business</span><span>Resources</span><span className="oa-nav-cta">Contact sales ↗</span></nav><section className="oa-web-hero"><div><span className="oa-eyebrow">Financial services / {asset.track==="Top 20"?asset.persona:"Workflow evaluation"}</span><h1>{asset.title}</h1><Copy asset={asset}/><Cta>{asset.cta}</Cta></div><Guide asset={asset}/></section><section className="oa-benefits"><h2>A practical framework.<br/>A shared next step.</h2><div>{[["01","Choose the workflow","Define the process and the question your team wants to answer."],["02","Bring the team together","Align business, technical and governance perspectives."],["03","Decide what to learn","Agree the evidence and the next decision before you begin."]].map(([n,h,p])=><article key={n}><span>{n}</span><h3>{h}</h3><p>{p}</p></article>)}</div></section><section className="oa-form-section"><div><span className="oa-eyebrow">Get the guide</span><h2>Start the conversation<br/>with your team.</h2><p>Receive the guide by email and explore a clearer path to evaluation.</p></div><div className="oa-form-preview" aria-label="Illustrative form, no data collection"><span>Work email</span><div>you@company.com</div><span>Company</span><div>Your organization</div><span>Your role</span><div>Select your role <span>⌄</span></div><p>We’ll use these details to deliver the guide. Contact preferences and privacy notice are confirmed before publication.</p><Cta>{asset.cta}</Cta></div></section><Footer/></div>;}
function Ad({asset}:{asset:Asset}){return <div className="oa-linkedin"><header className="oa-social-header"><span className="oa-social-avatar">O</span><div><b>OpenAI</b><small>Promoted</small></div><span>•••</span></header><div className="oa-social-intro"><Copy asset={asset}/></div><div className="oa-ad-art"><Mark/><span className="oa-eyebrow">Financial services</span><h1>{asset.title}</h1><div className="oa-ad-bottom"><span>{asset.persona||"For finance teams"}</span><span>Explore the guide ↗</span></div><div className="oa-ad-rules" aria-hidden="true"><i/><i/><i/><i/></div></div><div className="oa-link-card"><div><small>Guide · Financial services</small><b>{guideTitle(asset)}</b></div><span>{asset.cta}</span></div><footer className="oa-social-footer"><span>♡ Like</span><span>▢ Comment</span><span>↻ Repost</span><span>↗ Send</span></footer></div>;}
function Email({asset}:{asset:Asset}){const isRecap=asset.id.endsWith("recap"),isProof=asset.id.endsWith("proof");return <div className="oa-email"><div className="oa-inbox"><span>Inbox / Campaign preview</span><h2>{asset.title}</h2><div><b>OpenAI</b><span>To: {asset.persona||"Finance prospect"}</span></div></div><article className="oa-email-sheet"><header><Mark/><span>Financial services</span></header><div className="oa-email-hero"><span className="oa-eyebrow">{isRecap?"Continue the conversation":isProof?"A useful next step":"Your guide is ready"}</span><h1>{asset.title}</h1></div><div className="oa-email-body"><p>Hello,</p><Copy asset={asset}/><Cta>{asset.cta}</Cta>{!isRecap&&<div className="oa-email-resource"><Guide asset={asset} small/><div><span className="oa-eyebrow">Explore the framework</span><h3>{guideTitle(asset)}</h3><p>One workflow.<br/>The right people.<br/>A clear next step.</p></div></div>}{isRecap&&<div className="oa-next-steps"><span>Bring it back to your team</span><ol><li>Choose one workflow to explore.</li><li>Bring the relevant roles into the conversation.</li><li>Agree the next question to resolve.</li></ol></div>}<p>Best,<br/>The OpenAI team</p></div><Footer/></article></div>;}
function Event({asset}:{asset:Asset}){const top=asset.track==="Top 20";return <div className="oa-event"><header className="oa-site-nav"><Mark/><span>Financial services / Events</span></header><section className="oa-event-hero"><span className="oa-eyebrow">{top?"Virtual leaders roundtable":"Webinar"}</span><h1>{asset.title}</h1><div className="oa-event-meta"><span>{eventTiming(asset)}</span><span>Online</span></div><Cta>{asset.cta}</Cta><div className="oa-event-circles" aria-hidden="true"><i/><i/><i/></div></section><section className="oa-event-body"><div><h2>{top?"A conversation for the people moving work forward.":"From workflow interest to a practical evaluation."}</h2><Copy asset={asset}/></div><aside><span className="oa-eyebrow">What we’ll discuss</span><ol><li>Finding the right workflow to start with</li><li>Aligning business, technical and governance teams</li><li>Choosing the evidence for a next decision</li></ol><span className="oa-event-host">Hosts and final agenda to be confirmed</span></aside></section><Footer/></div>;}
function Sales({asset}:{asset:Asset}){return <div className="oa-sales"><header><Mark/><span>Internal / Sales enablement</span></header><div className="oa-sales-title"><span className="oa-eyebrow">{asset.track} · {asset.persona||"Finance prospects"}</span><h1>{asset.title}</h1><p>Context for a useful next conversation.</p></div><div className="oa-sales-grid"><section><h2>Why this contact, why now</h2><Copy asset={asset}/><div className="oa-sales-questions"><h3>Questions to bring to the conversation</h3><ol><li>Which workflow is the team evaluating?</li><li>Who needs to be involved in the decision?</li><li>What evidence would make the next step useful?</li></ol></div></section><aside><span className="oa-eyebrow">Account context</span><dl><dt>Account</dt><dd>Populated from the matched account</dd><dt>Role</dt><dd>{asset.persona||"Captured buying role"}</dd><dt>Guide</dt><dd>Confirmed download</dd><dt>Next signal</dt><dd>{asset.track==="Top 20"?"Roundtable response or meeting request":"Direct meeting request"}</dd><dt>Owner</dt><dd>{asset.track==="Top 20"?"Assigned Account Director":"Sales owner"}</dd></dl></aside></div><Footer/></div>;}
export default function FinservAssetMockup({asset,mobile=false}:{asset:Asset;mobile?:boolean}){return <div className={`oa-mockup${mobile?" oa-mobile":""}`} data-channel={asset.channel} aria-label={`${asset.track} ${asset.channel} visual mockup`}>
 {asset.channel==="LinkedIn / paid"?<Ad asset={asset}/>:asset.channel==="Web"?<Website asset={asset}/>:asset.channel==="Email"?<Email asset={asset}/>:asset.channel==="Events"?<Event asset={asset}/>:<Sales asset={asset}/>}
 </div>;}
