"use client";
import { useEffect, useState } from "react";
import { finservMeasures, finservResult, initialFinserv, type FinservInput } from "../lib/finserv";
import "./finserv-chat.css";
const key = "oai-morgan-finserv-chat-v1";
const titles = ["Campaign brief", "Journeys & work products", "Routing & Sales handoff", "December readout"];
const prompts = ["Build an October–November finance campaign for our Top 20 accounts and the wider market. Carry follow-through into December.", "Prepare both journeys and show what needs to be made.", "Show how a contact moves through the journey and what the Account Director receives.", "What should we measure and follow through on in December?"];
const replies = ["I’ll coordinate two journeys. Top 20 buying-group members receive tailored content and a virtual roundtable invitation. The broader finance audience includes Top 20 prospects and leads to a webinar. Once we identify a Top 20 contact, tailored follow-up takes priority.", "I’ve prepared the work package below. Email capture happens on the landing page; the guide email follows. A confirmed guide download unlocks the event invitation. Contacts who haven’t downloaded receive relevant proof and another guide offer.", "The Account Director receives role and engagement history after a Top 20 download. Registration, attendance or a direct meeting request prompts active follow-up. You can test those working rules below.", "I’ll connect engagement to Sales progression. The readout will distinguish campaign activity, account movement and pipeline evidence. Results stay pending until activation data is available."];
const assets = [
 ["LinkedIn / paid", "Account and buying-role ad variants", "Finance prospect ad", "Audience list, role definitions and creative review"],
 ["Web", "Tailored landing page + email capture", "Financial-workflow page + email capture", "Form fields, account matching and contact eligibility"],
 ["Email", "Leaders Guide delivery + relevant proof", "Guide delivery + relevant proof", "Approved guide and proof assets; download event"],
 ["Event", "Virtual roundtable invitation + reminders", "Webinar invitation + reminders", "Dates, hosts, registration pages and attendance records"],
 ["Sales", "Account Director context + follow-up", "Meeting requests routed to Sales; other contacts nurtured", "Named owner, role, engagement history and next action"],
];
export default function FinservChat() {
 const [stage, setStage] = useState(0), [opened, setOpened] = useState(0), [ready, setReady] = useState(false);
 const [input, setInput] = useState<FinservInput>(initialFinserv);
 const [role, setRole] = useState("Business sponsor"), [draft, setDraft] = useState(""), [notice, setNotice] = useState("");
 const [turns, setTurns] = useState<{prompt:string;reply:string}[]>([]);
 useEffect(() => { try { const raw = localStorage.getItem(key); if (raw) { const s = JSON.parse(raw); if (Number.isInteger(s.stage) && s.stage >= 0 && s.stage <= 3) { setStage(s.stage); setOpened(s.stage); } if (s.input) { const i=s.input; setInput({top20:i.top20===true,entry:i.entry==="broad"?"broad":"tailored",captured:i.captured===true,downloaded:i.captured===true&&i.downloaded===true,event:["registered","attended"].includes(i.event)?i.event:"none",meeting:i.captured===true&&i.meeting===true}); } if(typeof s.role==="string")setRole(s.role); if(Array.isArray(s.turns))setTurns(s.turns.filter((t: {prompt?:unknown;reply?:unknown})=>typeof t?.prompt==="string"&&typeof t?.reply==="string")); } } catch { setNotice("Saved Finserv conversation could not be loaded."); } setReady(true); },[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(key,JSON.stringify({stage,input,role,turns}));}catch{setNotice("Browser saving is unavailable. Download the work package to keep your inputs.");}},[ready,stage,input,role,turns]);
 const result=finservResult(input);
 function update(patch:Partial<FinservInput>){setInput(prev=>{const next={...prev,...patch};if(!next.captured){next.downloaded=false;next.meeting=false;}if(!next.downloaded)next.event="none";if(!next.top20)next.entry="broad";return next;});}
 function ask(){const prompt=draft.trim();if(!prompt)return;const reply=/december|measure|readout/i.test(prompt)?replies[3]:/sales|director|handoff/i.test(prompt)?replies[2]:/overlap|inclusive|top 20/i.test(prompt)?replies[0]:/download|email|guide/i.test(prompt)?replies[1]:"I’ve captured that direction for review with this Finserv brief. This guided prototype does not generate revised campaign copy; the prepared workflow and routing rules remain as shown.";setTurns(t=>[...t,{prompt,reply}]);setDraft("");}
 function download(){const text=`# Morgan’s Finserv work package\n\nGuided prototype; no live outreach.\n\n${titles.map((t,i)=>`## ${t}\n${replies[i]}`).join("\n\n")}\n\n${assets.map(a=>a.join(" | ")).join("\n")}\n\n## Simulated contact\nRole: ${role}\n${result.history.join("\n")}\nNext: ${result.next}\nSales: ${result.sales}\n\n## December measures\n${finservMeasures.map(m=>m.join(" — ")).join("\n")}\nTargets and results pending. Deduplicate campaign totals; report Top 20 as a subset.\n\n## Captured conversation\n${turns.map(t=>`Morgan: ${t.prompt}\nAgent: ${t.reply}`).join("\n\n")}`;const url=URL.createObjectURL(new Blob([text],{type:"text/markdown"}));const a=document.createElement("a");a.href=url;a.download="morgan-finserv-work-package.md";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="agent-product finserv-chat"><header><b>Marketing agent <span aria-hidden="true">⌄</span></b><span>Finserv · Top 20 + broader market</span></header><div className="agent-conversation">
 {notice&&<p role="status">{notice}</p>}
 {Array.from({length:stage+1},(_,i)=><div key={i} className="agent-followup"><div className="agent-prompt">{prompts[i]}</div><div className="agent-reply"><span className="agent-orb">✳</span><div><b>Marketing agent</b><p>{replies[i]}</p><button className="finserv-file" onClick={()=>setOpened(i)}>▤ {titles[i]} <span>Open work product ↗</span></button></div></div></div>)}
 <article className="artifact-preview work-artifact"><header><div><span className="agent-kicker">Finserv · illustrative work product</span><h3>{titles[opened]}</h3></div><button onClick={download}>Download</button></header>
 {opened===0&&<><p><b>Objective:</b> Generate engaged finance prospects, deepen Top 20 buying-group relationships and carry the context into Sales.</p><dl><dt>Activation</dt><dd>October–November · LinkedIn/paid, web, email, events and Sales</dd><dt>Follow-through</dt><dd>December · event recaps, Sales follow-up and campaign readout</dd><dt>Audience</dt><dd>All finance prospects, with an account/persona journey for buying-group members in the Top 20.</dd></dl><p><b>Coordination:</b> Identify the account at capture; suppress duplicate guide delivery and competing event invitations. Top 20 follow-up takes priority.</p><p><b>To confirm:</b> Top 20 list, approved guide and proof, event dates, Account Director owners and campaign targets.</p></>}
 {opened===1&&<><h4>Top 20 journey</h4><p>Account/persona ad → tailored landing page + email capture → Leaders Guide email → confirmed download → virtual roundtable invite → Account Director context and follow-up.</p><h4>Broader-market journey · inclusive</h4><p>Prospect ad → financial-workflow page + email capture → guide email → confirmed download → webinar invitation → follow-through.</p><div className="finserv-table"><table><thead><tr><th>Channel</th><th>Top 20</th><th>Broader market</th><th>Dependencies</th></tr></thead><tbody>{assets.map(a=><tr key={a[0]}>{a.map((c,i)=><td key={i}>{c}</td>)}</tr>)}</tbody></table></div><p><b>Working assumption:</b> Non-downloaders in both tracks get relevant proof, then another guide offer. Invitation timing and cadence are to be agreed.</p></>}
 {opened===2&&<><p>Change the signals to preview the next action. No emails or CRM tasks are sent.</p><fieldset disabled={!ready} className="finserv-controls"><label>Account<select value={input.top20?"top20":"broad"} onChange={e=>update({top20:e.target.value==="top20"})}><option value="top20">Top 20 finance account</option><option value="broad">Other finance account</option></select></label><label>Entry<select value={input.entry} onChange={e=>update({entry:e.target.value as FinservInput["entry"]})}>{input.top20&&<option value="tailored">Account/persona ad</option>}<option value="broad">Broader-market prospect ad</option></select></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}>{["Business sponsor","Technical evaluator","Procurement lead","Finance decision-maker"].map(r=><option key={r}>{r}</option>)}</select></label><label><input type="checkbox" checked={input.captured} onChange={e=>update({captured:e.target.checked})}/> Email captured</label><label><input type="checkbox" disabled={!input.captured} checked={input.downloaded} onChange={e=>update({downloaded:e.target.checked})}/> Confirmed guide download</label><label>Event response<select disabled={!input.downloaded} value={input.event} onChange={e=>update({event:e.target.value as FinservInput["event"]})}><option value="none">Not registered</option><option value="registered">Registered</option><option value="attended">Attended</option></select></label><label><input type="checkbox" disabled={!input.captured} checked={input.meeting} onChange={e=>update({meeting:e.target.checked})}/> Meeting requested</label></fieldset><div className="finserv-routing" aria-live="polite"><b>{input.captured?result.track:"Awaiting identification"}</b><p>Next: {result.next}</p><p>Sales: {result.sales}</p><p>Role: {input.captured?role:"Not yet captured"}</p><ul>{result.history.map(h=><li key={h}>{h}</li>)}</ul>{input.top20&&input.captured&&input.entry==="broad"&&<p>Top 20 match: switch to tailored follow-up; suppress the broader-market webinar invitation.</p>}</div><p>Working rule: download prepares Account Director context; registration, attendance or a meeting request prompts active follow-up. Other finance prospects stay in nurture unless they request a meeting.</p></>}
 {opened===3&&<><p><b>Results pending.</b> No performance figures are assumed. Agree targets after audience sizes, budget and baselines are available.</p>{finservMeasures.map(m=><section key={m[0]}><h4>{m[0]}</h4><p>{m[1]}</p><small>Evidence: {m[2]}</small></section>)}<p><b>Reporting rule:</b> Deduplicate campaign totals. Top 20 is a subset of the inclusive audience; do not add overlapping counts or sourced and influenced pipeline.</p><h4>December follow-through</h4><ol><li>Marketing sends event recaps and continues nurture.</li><li>Account Directors complete follow-ups and confirm meetings and opportunity movement.</li><li>Marketing operations reconciles web, email, event and CRM evidence.</li><li>Marketing and Sales assign next actions and agree changes for the next campaign.</li></ol></>}
 </article>
 {stage<3&&<button className="agent-primary" disabled={!ready} onClick={()=>{setStage(stage+1);setOpened(stage+1);}}>{["Prepare the journeys →","Review routing and Sales handoff →","Prepare December readout →"][stage]}</button>}
 {turns.map((t,i)=><div className="agent-followup" key={i}><div className="agent-prompt">{t.prompt}</div><div className="agent-reply"><span className="agent-orb">✳</span><div><b>Marketing agent</b><p>{t.reply}</p></div></div></div>)}
 <form className="agent-composer" onSubmit={e=>{e.preventDefault();ask();}}><label className="sr-only" htmlFor="finserv-message">Ask about the Finserv workflow</label><textarea id="finserv-message" rows={2} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Ask about this Finserv workflow" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();ask();}}}/><div><span>Guided prototype · no live tools</span><button type="submit" aria-label="Send message" disabled={!ready||!draft.trim()}>↑</button></div></form>
 </div></div>;
}
