import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import FinservAssetMockup from "../components/finserv-asset-mockup";
import { mockupStyles } from "./finserv-mockup-styles";
import { assetFormat, designNotes } from "./finserv-asset-design";
import type { Asset } from "./finserv-workflow";
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
export function assetDocument(assets:Asset[],revision:number,mobile=false){
 const pages=assets.map((asset,i)=>`<section class="export-page" id="asset-${i}"><header class="export-label"><span>${escape(asset.track)} / ${escape(asset.persona||"All finance roles")} / ${escape(asset.channel)}</span><span>${escape(assetFormat(asset))}</span></header>${renderToStaticMarkup(createElement(FinservAssetMockup,{asset,mobile}))}<footer class="export-note">Concept mockup · packet revision ${revision} · no live form, email or ad</footer></section>`).join("\n");
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>Finserv visual work package — revision ${revision}</title><style>${mockupStyles}\nbody{margin:0;background:#efefeb;color:#171717;font-family:Arial,sans-serif}.export-intro{max-width:1040px;margin:50px auto;padding:0 24px}.export-intro h1{font-size:32px;letter-spacing:-1px;font-weight:400}.export-intro p{font-size:13px;line-height:1.6}.export-intro a{color:inherit}.export-page{max-width:1040px;margin:0 auto 70px;padding:0 24px}.export-label{display:flex;flex-wrap:wrap;gap:12px;justify-content:space-between;margin:0 0 15px;font-size:12px}.export-note{font-size:11px;color:#666;padding:12px 0}.export-index{display:flex;gap:8px 20px;flex-wrap:wrap;padding:20px 0}.export-index a{font-size:12px}@media print{body{background:white}.export-intro{break-after:page}.export-page{break-before:page;margin:0;padding:0}.oa-mockup{box-shadow:none}.export-index{display:none}*{-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style></head><body><header class="export-intro"><h1>Finserv visual work package</h1><p>${assets.length} ${assets.length===1?"mockup":"mockups"} · packet revision ${revision} · ${mobile?"Mobile":"Desktop"} layout</p><p>${escape(designNotes.status)} ${escape(designNotes.font)}</p><p>Reference: <a href="${designNotes.reference}">OpenAI’s public design guidelines</a>. All previews are inert; no forms submit and no messages send.</p><nav class="export-index" aria-label="Mockup index">${assets.map((a,i)=>`<a href="#asset-${i}">${i+1}. ${escape(a.track)} / ${escape(a.persona||"All roles")} / ${escape(a.channel)} / ${escape(a.title)}</a>`).join("")}</nav></header>${pages}</body></html>`;
}
